### ISSUE TITLE
Embedded libgraphqlparser build fails with latest ctypesgen

### ISSUE THREAD

**Issue by bobh66** [tartiflette/tartiflette#301] opened 2019-09-21 13:08 UTC
## Report a bug

* [X] **Explain with a simple sentence the expected behavior**
The build of the embedded libgraphqlparser fails with the latest ctypesgen module.

* [X] **Tartiflette version:**  - latest

* [X] **Python version:** _3.6, 3.7_

Since ctypesgen 0.1.1 (now 1.0.0) it has installed as "ctypesgen" instead of "ctypesgen.py".

The CMakeLists.txt for libgraphqlparser only looks for "ctypesgen.py" and doesn't find "ctypesgen".

I pushed a PR to the tartiflette/libgraphqlparser repo/branch that holds the Py3 version of  libgraphqlparser to fix the CMakeLists.txt file to look for ctypesgen if it can't find ctypesgen.py, and I will submit the same change upstream to libgraphqlparser .

* [X] **Executed in docker:** _No_
* [X] **Dockerfile sample:** N/A
* [X] **GraphQL Schema & Query:** N/A
* [X] **Is it a regression from a previous versions?** _No_
* [X] **Stack trace** N/A

**Comment by abusi** [comment] 2019-09-23 08:46
I'll wait a littlebit for a reaction on the official repo, if they merge it, i'll rebase. If nothing happens there, i'll merge you PR on tartiflette/libgraphqlparser and release a tartiflette 1.x.y with it.
And, tartiflette don't need all this python2 things and I don't want to have to maintain all this.
I don't responsability over libgraphqlparser.
We'll see how it goes. Maybe we'll really fork completly and even remove all this python2 thing. If someone is interested in maintaining it. 
I hope the graphql/libgraphqlparser will be updated on the latest GraphQL Spec.
We'll see how it's going in on when it happens.

**Comment by florimondmanca** [comment] 2019-10-03 06:36
I also encountered this while trying to upgrade to 1.0 to try out `tartiflette-starlette` on that version.

Link to the issue on the upstream repo: https://github.com/graphql/libgraphqlparser/issues/89

**Comment by florimondmanca** [comment] 2019-10-03 06:43
> And, tartiflette don't need all this python2 things

I can confirm that installing Tartiflette requires the `python2` to be available — not sure if this is new (I reinstalled 0.12.5). I had to tweak my pyenv setup to account for this:

```console
$ pyenv global 3.7.3 3.6.8 2.7.15 3.8-dev
```

**Comment by abusi** [comment] 2019-10-03 13:47
> > And, tartiflette don't need all this python2 things
> 
> I can confirm that installing Tartiflette requires the `python2` to be available — not sure if this is new (I reinstalled 0.12.5). I had to tweak my pyenv setup to account for this:
> 
> ```
> $ pyenv global 3.7.3 3.6.8 2.7.15 3.8-dev
> ```

Yes, what I mean is that it shouldn't need it. but it's mandatory in the cmakelist of libgraphqlparser.
I don't really know what to do here, cause if I update my branch on my libgraphqlparser, it will go farther from libgraphqlparser main repo, and I really don't want to have to maintain a fork.
I'll see if I found the time to think of something, or at least to finish working for my branch to be merged.
It also looks like the project `libgraphqlparser` is kind of abandonned ... maybe forking away is not that bad of an idea ... IDK.

Do you have any idea on how we could get rid of this problem? (fastness of tartiflette partly come from using this C++ lib to parse the requests.)

**Comment by florimondmanca** [comment] 2019-10-09 07:44
Is there any way we can restrict the version of ctypesgen to 0.x on our side? Or maybe push the fix from https://github.com/graphql/libgraphqlparser/pull/90 to our fork and release it while things get sorted out on the official repo?

I'm still encountering this issue on macOS Mojave / Python 3.7.4 / Tartiflette 1.1.0, and this is definitely blocking other users from upgrading to Tartiflette 1.0.

I'm curious why Travis CI builds over at https://github.com/tartiflette/tartiflette-starlette/pull/58 don't catch this compilation error (is it not happening on Linux?), but adding 1.0 support to `tartiflette-starlette` is also blocked because of this at the moment unfortunately.

**Comment by florimondmanca** [comment] 2019-10-09 07:51
As for the Python 2 issue,

> but it's mandatory in the cmakelist of libgraphqlparser

Would pushing (as in: contributing) for upgrading the Python 2 scripts in `graphql/libgraphqlparser` to Python 3 be acceptable?

You wrote:

> I don't want responsability over libgraphqlparser.

In my point of view though, `libgraphqlparser` *is* our responsability — we're using it to power our parser layer; it's an important dependency, and we should care for it.

If people from the main repo don't have the resources/interest to make what we need happen, perhaps scratching our own itch and contributing back is reasonable.

If they stay unresponsive though, either we find new maintainership for the main repo, we hard fork, or we use a different parser. But I think the state of `libgraphqlparser` is very much *our* problem too.

**Comment by abusi** [comment] 2019-10-09 08:32
@florimondmanca 
I think that it is what i'm going to do. I'm going to clean the tartiflette/libgraphqlparser repository from everything that is python2 dependant. and use this version in tartiflette and produce a 1.1.1 with it.

In the end, we need it to work. What I mean in my previous comment is that I may not have the time to take care of it. But in the end it is very important, so I'll have to do it.

Thanks for your advices.

**Comment by abusi** [comment] 2019-10-09 11:43
@bobh66 Can you try using `pip install -i https://test.pypi.org/simple tartiflette==1.1.1.dev1570620494 --extra-index-url https://pypi.org/simple` and tell me if it's working for you ? Thanks.

**Closed** 2019-10-10 09:06 UTC
